_target_: eile_forecast.forecast.split_data.GluontsDatasetEile
add_holidays_and_weekends: true
add_seasonalities: true
add_weather: false
benchmark_end_date: 2017-10-12 22:00
benchmark_start_date: 2015-11-28 06:00
country: Germany
forecast_signal: load
main_signal_name: load
name: Cosmic1
